---
# MAINTAINER louis.hong@junhsue.com
# 初始化新云主机, 包含jdk, sysctl优化, security优化, ulimits优化
- hosts: yj-new
  remote_user: root
  tasks:
  - name:  copy jdk to nodes
    copy:
      src: /opt/playbook/devops/project/jdk-8u181-linux-x64.tar.gz
      dest: /usr/local/jdk-8u181-linux-x64.tar.gz

  - name: copy systcl to nodes
    copy:
      src: /opt/playbook/tpl/sysctl.conf
      dest: /etc/sysctl.conf

  - name: copy ulimits.sh to nodes
    copy:  
      src: /opt/playbook/tpl/ulimit.sh
      dest: /etc/profile.d/ulimit.sh

  - name: copy security/limits.conf to nodes
    copy:
      src: /opt/playbook/tpl/limits.conf
      dest: /etc/security/limits.conf

  - name: tar xf jdk
    shell: "cd /usr/local && tar xf jdk-8u181-linux-x64.tar.gz -C /usr/local"
