---
# MAINTAINER louis.hong@junhsue.com
#
- hosts: yj-font
  remote_user: root
  tasks:
    - name: make dir if not exsit
      shell: test -d /data/{{item}} || mkdir /data/{{item}} -p
      with_items:
        - test01
        - test02
    - name:  copy template to nodes
      template:
        src: /opt/playbook/devops/tpl/test.t2
        dest: /data/{{item}}/test.sh
      with_items:
        - test01
        - test02
    - name: sed port in files
      replace: dest=/data/{{item.name}}/test.sh regexp="8888" replace="{{item.port}}"
      with_items:
        - { name: 'test01', port: '22332' }
        - { name: 'test02', port: '22333' }
    - name: count time
      shell: "sleep 2s && cd /data/{{item}}/ && echo 1 >> test.log"
      with_items:
        - test01
        - test02